### ISSUE TITLE
'function' object has no attribute 'get_full_path'

### ISSUE THREAD

**Issue by BakanovKirill** [gregmuellegger/django-mobile#24]
This is my url in urls.py:

('^', cache_page(IndexView.as_view(), CACHE_TIMEOUT, key_prefix=CACHE_PREFIX), {}, 'index'),

I get this error when i use django_mobile.cache.cache_page decorator:
'function' object has no attribute 'get_full_path'

Should i place CacheFlavourMiddleware somewhere?

**Comment by gregmuellegger** [comment]
Hi, this issue was reported quite a while back. Please feel to re-open if you feel that it is still valid.
