### ISSUE TITLE
Adding Python 3 support

### ISSUE THREAD

**Issue by machakux** [gregmuellegger/django-mobile#34]
Now Django support for Python 3 can be considered as stable, I think it won't be a bad idea to start porting this app to Python 3.

I tried to make it work with Python 3 and it seems to work. I haven't done much testing that's why I haven't initialized a pull request.

Here is my code: https://github.com/machakux/django-mobile .

**Comment by gregmuellegger** [comment]
We are testing successfully against Python 3 since the 0.4.0 release :)
https://travis-ci.org/gregmuellegger/django-mobile
