### ISSUE TITLE
Android tablet not recog as mobile

### ISSUE THREAD

**Issue by seocam** [gregmuellegger/django-mobile#39]
django-mobile is not able to tell me I'm in a mobile device when accessing from an Android tablet. This problem occurs in every browser I've tested.

Follow the user agents:

Android browser: `Mozilla/5.0 (Linux; U; Android 4.0.4; en-us; GT-P7510 Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30`

Firefox for Android: `Mozilla/5.0 (Android; Tablet; rv:29.0) Gecko/29.0 Firefox/29.0`

Chrome for Android: `Mozilla/5.0 (Linux; Android 4.0.4; GT-P7510 Build/IMM76D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.141 Safari/537.36`

**Comment by gregmuellegger** [comment]
We now have an example of a custom middleware: Please use this as the base to roll your own mobile detection middleware.

**Comment by gregmuellegger** [comment]
Forgot to link to it :) here it is https://github.com/gregmuellegger/django-mobile/blob/master/examples/middleware.py
