### ISSUE TITLE
No option to provide empty exceptions

### ISSUE THREAD

**Issue by Gandi24** [gregmuellegger/django-mobile#49]
There is not possibility to provide empty list of exceptions search.

The default one is:
user_agents_exception_search = u"(?:%s)" % u'|'.join((
    'ipad',
))

Providing:
user_agents_exception_search = u"(?:%s)" % u'|'.join((
))
crushes the detection.

**Comment by gregmuellegger** [comment]
Hi, as a work around you can set:

```
user_agents_exception_search = "(?!)"
```

That sets the search term to a regular expression that will never match anything.
