### ISSUE TITLE
CachedLoader is broken on Django 1.7

### ISSUE THREAD

**Issue by igalarzab** [gregmuellegger/django-mobile#50]
Django has changed the way it finds templates [1] in Django 1.7 and now it's necessary to overwrite ``find_template`` to recreate the key, prepending the flavour as in ``load_template``.

[1] https://github.com/django/django/blob/master/django/template/loaders/cached.py#L36

**Comment by connorgorman** [comment]
Was this ever merged?

**Comment by gregmuellegger** [comment]
It was just merged :) Sorry for the long wait.
