### ISSUE TITLE
no flavour cookie

### ISSUE THREAD

**Issue by bung87** [gregmuellegger/django-mobile#59]
I followed the installation steps except 5 and 6

**Comment by gregmuellegger** [comment]
A cookie is only set when you force a flavour. In which situation do you expect a cookie to be set, can you post the actual response headers that should set the cookie but didn't?

**Comment by bung87** [comment]
I would like to store the flavour at user's browser,then detemine initial page size of api results.

**Comment by gregmuellegger** [comment]
Like I said, the cookie will be set the first time when the `?flavour=...` GET parameter is used.
You can read the currently active flavour with `django_mobile.get_flavour`

**Comment by bung87** [comment]
oh,I just thought it will be set when detected the flavour,if I use get_flavour multi-time,It may becoming inefficient

**Comment by gregmuellegger** [comment]
Why would you think that, the implementation is really simple: https://github.com/gregmuellegger/django-mobile/blob/master/django_mobile/__init__.py#L78

**Comment by bung87** [comment]
looks really simple! If I set the store_backend to cookie,and ?flavour=... not presented ,it will looks into request object then  _local variable which stores flavour  in threading.local(),thank god,First time heard of threading.local(),Thank your for answerd my question.

**Comment by gregmuellegger** [comment]
:) Have fun using it.
