### ISSUE TITLE
Skip mobile detection after flavour is saved permanently

### ISSUE THREAD

**Issue by likang** [gregmuellegger/django-mobile#61]
Hi, thanks for this great middleware! 

After reading the source around, I found that MobileDetectionMiddleware will work on every request, which I think maybe is not necessary. If the flavour is saved in backend, why not just read it?

Or there is something I have missed >_<

**Comment by gregmuellegger** [comment]
Hm, actually this might be an inefficiency, that's true. However I wanted to keep the detection and storage in two separate middlewares in order to separate two different concerns. That way you can use the same detection logic with a different storage middleware and vice versa.

**Comment by tisdall** [comment]
I came to mention the same thing and found this issue...  Perhaps a third middleware that could be used instead that would make short-circuit calls to the other 2 middlewares?

**Comment by gregmuellegger** [comment]
That could work yes. However I won't add this to django-mobile as I'm still in favour of the distinct responsibilities of the middlewares and I don't want to disguise this.

But I would be happy about any pull requests that improve the documentation in that part, on how to write your own detection/saving middleware to save resources. Or on how a middleware might look that short-circuits the calls like suggested by @tisdall.
