### ISSUE TITLE
Adding smart watch flavour ?

### ISSUE THREAD

**Issue by sunjoomoon** [gregmuellegger/django-mobile#65]
I am trying out things and wondered how I can add another flavour, from the doc it seems it could be implemented rather easy. Any clue as to how I could do this?

**Comment by gregmuellegger** [comment]
What have you tried so far?

I think it's just adding another name to the `FLAVOURS` setting:

```python
# in settings.py
FLAVOURS = ('full', 'mobile', 'tablet')
```

**Comment by sunjoomoon** [comment]
Hmm, just like that? I am all lost.

**Comment by prokaktus** [comment]
@sunjoomoon look at the example for tablet detection https://github.com/gregmuellegger/django-mobile/blob/master/examples/middleware.py

You should investigate how to detect smart watch browsers (by user-agent or another header), write custom rule and add new flavour to `FLAVOURS` setting.

**Comment by sunjoomoon** [comment]
Thanks, sorry for long absence. Yes, now it makes sense.
