### ISSUE TITLE
Got 'django.template.loader_tags.ExtendsError' when customizing admin interface in Django 1.9

### ISSUE THREAD

**Issue by wolfg1969** [gregmuellegger/django-mobile#68]
I have customizedd admin page by extending 'admin/base_site.html' template. The admin page is broken after add 'django_mobile.loader.Loader' to loaders of TEMPLATES settings. The error is 'ExtendsError: Cannot extend templates recursively when using non-recursive template loaders'.

My TEMPLATES Settings is below:

``` python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'django_mobile.context_processors.flavour',
            ],
            'loaders': [
                'django_mobile.loader.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ]
        },
    },
]
```

**Comment by gregmuellegger** [comment]
Seems like that is a matter of implementing the `get_contents` method on the mobile loader. See here: https://github.com/django/django/blob/master/django/template/loaders/base.py#L104

I think I won't get to that soonish.

@wolfg1969 would you like to create a pull request to solve this issue?

**Comment by wolfg1969** [comment]
ok, I'll try it.
